{% set version = "1.12.0" %}

package:
  name: prrng-split
  version: {{ version }}

source:
  url: https://github.com/tdegeus/prrng/archive/v{{ version }}.tar.gz
  sha256: 638788b382af6de5779fe7605039731c23c85e551b3fb15c941dd231b0e5762f

build:
  number: 1

outputs:

  - name: prrng

    script: install.sh  # [unix]
    script: install.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - boost-cpp
        - xtensor
      run:
        - boost-cpp
        - xtensor

    test:
      commands:
        - test -f ${PREFIX}/include/prrng.h                                 # [unix]
        - test -f ${PREFIX}/lib/cmake/prrng/prrngConfig.cmake               # [unix]
        - if not exist %LIBRARY_PREFIX%\include\prrng.h exit 1              # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\prrngConfig.cmake exit 1  # [win]

  - name: python-prrng

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
      skip: true  # [python_impl == 'pypy']

    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy *                             # [build_platform != target_platform]
        - setuptools_scm                      # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - ninja
      host:
        - boost-cpp
        - numpy *
        - pip
        - pybind11
        - pybind11-abi
        - python
        - scikit-build
        - setuptools_scm
        - xtensor
        - xtensor-python
      run:
        - numpy *
        - python

    test:
      imports:
        - prrng
      commands:
        - pip check
        - python -c "import prrng; assert prrng.version() == '{{ version }}'"
      requires:
        - pip

about:
  home: https://github.com/tdegeus/prrng
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Portable Reconstructible (Pseudo) Random Number Generator.
  description: Portable Reconstructible (Pseudo) Random Number Generator.
  doc_url: https://tdegeus.github.io/prrng
  dev_url: https://github.com/tdegeus/prrng

extra:
  recipe-maintainers:
    - tdegeus
